// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: backup.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

#if canImport(FoundationEssentials)
import FoundationEssentials
#else
import Foundation
#endif
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

/// Logical personal-data snapshot. Gzip this message once; hash compressed bytes.
/// IDs and chart keys are stable application IDs. Timestamps are Unix milliseconds.
/// Zero optional timestamps and empty optional strings mean absent. Never include tokens.
nonisolated struct RHYSnapshot: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// RHYTHMETA_BACKUP
  var magic: String = String()

  /// 1
  var formatVersion: UInt32 = 0

  /// maimaid or chunithmd
  var game: String = String()

  var createdAt: Int64 = 0

  var clientVersion: String = String()

  var profiles: [RHYProfile] = []

  var scores: [RHYScore] = []

  var playRecords: [RHYPlayRecord] = []

  var collections: [RHYCollection] = []

  var collectionItems: [RHYCollectionItem] = []

  var favoriteSongIds: [String] = []

  var settings: [RHYSetting] = []

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

nonisolated struct RHYProfile: @unchecked Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var id: String {
    get {_storage._id}
    set {_uniqueStorage()._id = newValue}
  }

  var name: String {
    get {_storage._name}
    set {_uniqueStorage()._name = newValue}
  }

  var server: String {
    get {_storage._server}
    set {_uniqueStorage()._server = newValue}
  }

  var avatar: Data {
    get {_storage._avatar}
    set {_uniqueStorage()._avatar = newValue}
  }

  var avatarURL: String {
    get {_storage._avatarURL}
    set {_uniqueStorage()._avatarURL = newValue}
  }

  var active: Bool {
    get {_storage._active}
    set {_uniqueStorage()._active = newValue}
  }

  var createdAt: Int64 {
    get {_storage._createdAt}
    set {_uniqueStorage()._createdAt = newValue}
  }

  var dfUsername: String {
    get {_storage._dfUsername}
    set {_uniqueStorage()._dfUsername = newValue}
  }

  var playerRating: Int32 {
    get {_storage._playerRating}
    set {_uniqueStorage()._playerRating = newValue}
  }

  var plate: String {
    get {_storage._plate}
    set {_uniqueStorage()._plate = newValue}
  }

  var lastImportDf: Int64 {
    get {_storage._lastImportDf}
    set {_uniqueStorage()._lastImportDf = newValue}
  }

  var lastImportLxns: Int64 {
    get {_storage._lastImportLxns}
    set {_uniqueStorage()._lastImportLxns = newValue}
  }

  var b35Count: Int32 {
    get {_storage._b35Count}
    set {_uniqueStorage()._b35Count = newValue}
  }

  var b15Count: Int32 {
    get {_storage._b15Count}
    set {_uniqueStorage()._b15Count = newValue}
  }

  var b35RecLimit: Int32 {
    get {_storage._b35RecLimit}
    set {_uniqueStorage()._b35RecLimit = newValue}
  }

  var b15RecLimit: Int32 {
    get {_storage._b15RecLimit}
    set {_uniqueStorage()._b15RecLimit = newValue}
  }

  var title: String {
    get {_storage._title}
    set {_uniqueStorage()._title = newValue}
  }

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

nonisolated struct RHYScore: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var profileID: String = String()

  var chartKey: String = String()

  var achievement: Double = 0

  var rank: String = String()

  var dxScore: Int32 = 0

  var fc: String = String()

  var fs: String = String()

  var achievedAt: Int64 = 0

  var score: Int32 = 0

  var clear: String = String()

  var songID: String = String()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

nonisolated struct RHYPlayRecord: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var id: String = String()

  var result: RHYScore {
    get {_result ?? RHYScore()}
    set {_result = newValue}
  }
  /// Returns true if `result` has been explicitly set.
  var hasResult: Bool {self._result != nil}
  /// Clears the value of `result`. Subsequent reads from it will return its default value.
  mutating func clearResult() {self._result = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _result: RHYScore? = nil
}

nonisolated struct RHYCollection: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var id: String = String()

  var name: String = String()

  var sortIndex: Int32 = 0

  var createdAt: Int64 = 0

  var updatedAt: Int64 = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

nonisolated struct RHYCollectionItem: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var id: String = String()

  var collectionID: String = String()

  var songID: String = String()

  var chartType: String = String()

  var difficulty: String = String()

  var position: Int32 = 0

  var createdAt: Int64 = 0

  var updatedAt: Int64 = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

/// Namespaced platform settings remain portable as opaque values to the other OS.
/// Only an explicit allowlist of personal settings may be imported or exported.
nonisolated struct RHYSetting: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var key: String = String()

  /// string, int, long, double, float, bool, strings, bytes
  var kind: String = String()

  var stringValue: String = String()

  var integerValue: Int64 = 0

  var doubleValue: Double = 0

  var boolValue: Bool = false

  var stringValues: [String] = []

  var bytesValue: Data = Data()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate nonisolated let _protobuf_package = "rhythmeta.backup.v1"

nonisolated extension RHYSnapshot: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".Snapshot"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}magic\0\u{3}format_version\0\u{1}game\0\u{3}created_at\0\u{3}client_version\0\u{1}profiles\0\u{1}scores\0\u{3}play_records\0\u{1}collections\0\u{3}collection_items\0\u{3}favorite_song_ids\0\u{1}settings\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.magic) }()
      case 2: try { try decoder.decodeSingularUInt32Field(value: &self.formatVersion) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.game) }()
      case 4: try { try decoder.decodeSingularInt64Field(value: &self.createdAt) }()
      case 5: try { try decoder.decodeSingularStringField(value: &self.clientVersion) }()
      case 6: try { try decoder.decodeRepeatedMessageField(value: &self.profiles) }()
      case 7: try { try decoder.decodeRepeatedMessageField(value: &self.scores) }()
      case 8: try { try decoder.decodeRepeatedMessageField(value: &self.playRecords) }()
      case 9: try { try decoder.decodeRepeatedMessageField(value: &self.collections) }()
      case 10: try { try decoder.decodeRepeatedMessageField(value: &self.collectionItems) }()
      case 11: try { try decoder.decodeRepeatedStringField(value: &self.favoriteSongIds) }()
      case 12: try { try decoder.decodeRepeatedMessageField(value: &self.settings) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.magic.isEmpty {
      try visitor.visitSingularStringField(value: self.magic, fieldNumber: 1)
    }
    if self.formatVersion != 0 {
      try visitor.visitSingularUInt32Field(value: self.formatVersion, fieldNumber: 2)
    }
    if !self.game.isEmpty {
      try visitor.visitSingularStringField(value: self.game, fieldNumber: 3)
    }
    if self.createdAt != 0 {
      try visitor.visitSingularInt64Field(value: self.createdAt, fieldNumber: 4)
    }
    if !self.clientVersion.isEmpty {
      try visitor.visitSingularStringField(value: self.clientVersion, fieldNumber: 5)
    }
    if !self.profiles.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.profiles, fieldNumber: 6)
    }
    if !self.scores.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.scores, fieldNumber: 7)
    }
    if !self.playRecords.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.playRecords, fieldNumber: 8)
    }
    if !self.collections.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.collections, fieldNumber: 9)
    }
    if !self.collectionItems.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.collectionItems, fieldNumber: 10)
    }
    if !self.favoriteSongIds.isEmpty {
      try visitor.visitRepeatedStringField(value: self.favoriteSongIds, fieldNumber: 11)
    }
    if !self.settings.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.settings, fieldNumber: 12)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: RHYSnapshot, rhs: RHYSnapshot) -> Bool {
    if lhs.magic != rhs.magic {return false}
    if lhs.formatVersion != rhs.formatVersion {return false}
    if lhs.game != rhs.game {return false}
    if lhs.createdAt != rhs.createdAt {return false}
    if lhs.clientVersion != rhs.clientVersion {return false}
    if lhs.profiles != rhs.profiles {return false}
    if lhs.scores != rhs.scores {return false}
    if lhs.playRecords != rhs.playRecords {return false}
    if lhs.collections != rhs.collections {return false}
    if lhs.collectionItems != rhs.collectionItems {return false}
    if lhs.favoriteSongIds != rhs.favoriteSongIds {return false}
    if lhs.settings != rhs.settings {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension RHYProfile: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".Profile"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}id\0\u{1}name\0\u{1}server\0\u{1}avatar\0\u{3}avatar_url\0\u{1}active\0\u{3}created_at\0\u{3}df_username\0\u{3}player_rating\0\u{1}plate\0\u{3}last_import_df\0\u{3}last_import_lxns\0\u{3}b35_count\0\u{3}b15_count\0\u{3}b35_rec_limit\0\u{3}b15_rec_limit\0\u{1}title\0")

  fileprivate class _StorageClass {
    var _id: String = String()
    var _name: String = String()
    var _server: String = String()
    var _avatar: Data = Data()
    var _avatarURL: String = String()
    var _active: Bool = false
    var _createdAt: Int64 = 0
    var _dfUsername: String = String()
    var _playerRating: Int32 = 0
    var _plate: String = String()
    var _lastImportDf: Int64 = 0
    var _lastImportLxns: Int64 = 0
    var _b35Count: Int32 = 0
    var _b15Count: Int32 = 0
    var _b35RecLimit: Int32 = 0
    var _b15RecLimit: Int32 = 0
    var _title: String = String()

      // This property is used as the initial default value for new instances of the type.
      // The type itself is protecting the reference to its storage via CoW semantics.
      // This will force a copy to be made of this reference when the first mutation occurs;
      // hence, it is safe to mark this as `nonisolated(unsafe)`.
      static nonisolated(unsafe) let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _id = source._id
      _name = source._name
      _server = source._server
      _avatar = source._avatar
      _avatarURL = source._avatarURL
      _active = source._active
      _createdAt = source._createdAt
      _dfUsername = source._dfUsername
      _playerRating = source._playerRating
      _plate = source._plate
      _lastImportDf = source._lastImportDf
      _lastImportLxns = source._lastImportLxns
      _b35Count = source._b35Count
      _b15Count = source._b15Count
      _b35RecLimit = source._b35RecLimit
      _b15RecLimit = source._b15RecLimit
      _title = source._title
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every case branch when no optimizations are
        // enabled. https://github.com/apple/swift-protobuf/issues/1034
        switch fieldNumber {
        case 1: try { try decoder.decodeSingularStringField(value: &_storage._id) }()
        case 2: try { try decoder.decodeSingularStringField(value: &_storage._name) }()
        case 3: try { try decoder.decodeSingularStringField(value: &_storage._server) }()
        case 4: try { try decoder.decodeSingularBytesField(value: &_storage._avatar) }()
        case 5: try { try decoder.decodeSingularStringField(value: &_storage._avatarURL) }()
        case 6: try { try decoder.decodeSingularBoolField(value: &_storage._active) }()
        case 7: try { try decoder.decodeSingularInt64Field(value: &_storage._createdAt) }()
        case 8: try { try decoder.decodeSingularStringField(value: &_storage._dfUsername) }()
        case 9: try { try decoder.decodeSingularInt32Field(value: &_storage._playerRating) }()
        case 10: try { try decoder.decodeSingularStringField(value: &_storage._plate) }()
        case 11: try { try decoder.decodeSingularInt64Field(value: &_storage._lastImportDf) }()
        case 12: try { try decoder.decodeSingularInt64Field(value: &_storage._lastImportLxns) }()
        case 13: try { try decoder.decodeSingularInt32Field(value: &_storage._b35Count) }()
        case 14: try { try decoder.decodeSingularInt32Field(value: &_storage._b15Count) }()
        case 15: try { try decoder.decodeSingularInt32Field(value: &_storage._b35RecLimit) }()
        case 16: try { try decoder.decodeSingularInt32Field(value: &_storage._b15RecLimit) }()
        case 17: try { try decoder.decodeSingularStringField(value: &_storage._title) }()
        default: break
        }
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      if !_storage._id.isEmpty {
        try visitor.visitSingularStringField(value: _storage._id, fieldNumber: 1)
      }
      if !_storage._name.isEmpty {
        try visitor.visitSingularStringField(value: _storage._name, fieldNumber: 2)
      }
      if !_storage._server.isEmpty {
        try visitor.visitSingularStringField(value: _storage._server, fieldNumber: 3)
      }
      if !_storage._avatar.isEmpty {
        try visitor.visitSingularBytesField(value: _storage._avatar, fieldNumber: 4)
      }
      if !_storage._avatarURL.isEmpty {
        try visitor.visitSingularStringField(value: _storage._avatarURL, fieldNumber: 5)
      }
      if _storage._active != false {
        try visitor.visitSingularBoolField(value: _storage._active, fieldNumber: 6)
      }
      if _storage._createdAt != 0 {
        try visitor.visitSingularInt64Field(value: _storage._createdAt, fieldNumber: 7)
      }
      if !_storage._dfUsername.isEmpty {
        try visitor.visitSingularStringField(value: _storage._dfUsername, fieldNumber: 8)
      }
      if _storage._playerRating != 0 {
        try visitor.visitSingularInt32Field(value: _storage._playerRating, fieldNumber: 9)
      }
      if !_storage._plate.isEmpty {
        try visitor.visitSingularStringField(value: _storage._plate, fieldNumber: 10)
      }
      if _storage._lastImportDf != 0 {
        try visitor.visitSingularInt64Field(value: _storage._lastImportDf, fieldNumber: 11)
      }
      if _storage._lastImportLxns != 0 {
        try visitor.visitSingularInt64Field(value: _storage._lastImportLxns, fieldNumber: 12)
      }
      if _storage._b35Count != 0 {
        try visitor.visitSingularInt32Field(value: _storage._b35Count, fieldNumber: 13)
      }
      if _storage._b15Count != 0 {
        try visitor.visitSingularInt32Field(value: _storage._b15Count, fieldNumber: 14)
      }
      if _storage._b35RecLimit != 0 {
        try visitor.visitSingularInt32Field(value: _storage._b35RecLimit, fieldNumber: 15)
      }
      if _storage._b15RecLimit != 0 {
        try visitor.visitSingularInt32Field(value: _storage._b15RecLimit, fieldNumber: 16)
      }
      if !_storage._title.isEmpty {
        try visitor.visitSingularStringField(value: _storage._title, fieldNumber: 17)
      }
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: RHYProfile, rhs: RHYProfile) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._id != rhs_storage._id {return false}
        if _storage._name != rhs_storage._name {return false}
        if _storage._server != rhs_storage._server {return false}
        if _storage._avatar != rhs_storage._avatar {return false}
        if _storage._avatarURL != rhs_storage._avatarURL {return false}
        if _storage._active != rhs_storage._active {return false}
        if _storage._createdAt != rhs_storage._createdAt {return false}
        if _storage._dfUsername != rhs_storage._dfUsername {return false}
        if _storage._playerRating != rhs_storage._playerRating {return false}
        if _storage._plate != rhs_storage._plate {return false}
        if _storage._lastImportDf != rhs_storage._lastImportDf {return false}
        if _storage._lastImportLxns != rhs_storage._lastImportLxns {return false}
        if _storage._b35Count != rhs_storage._b35Count {return false}
        if _storage._b15Count != rhs_storage._b15Count {return false}
        if _storage._b35RecLimit != rhs_storage._b35RecLimit {return false}
        if _storage._b15RecLimit != rhs_storage._b15RecLimit {return false}
        if _storage._title != rhs_storage._title {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension RHYScore: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".Score"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}profile_id\0\u{3}chart_key\0\u{1}achievement\0\u{1}rank\0\u{3}dx_score\0\u{1}fc\0\u{1}fs\0\u{3}achieved_at\0\u{1}score\0\u{1}clear\0\u{3}song_id\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.profileID) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.chartKey) }()
      case 3: try { try decoder.decodeSingularDoubleField(value: &self.achievement) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.rank) }()
      case 5: try { try decoder.decodeSingularInt32Field(value: &self.dxScore) }()
      case 6: try { try decoder.decodeSingularStringField(value: &self.fc) }()
      case 7: try { try decoder.decodeSingularStringField(value: &self.fs) }()
      case 8: try { try decoder.decodeSingularInt64Field(value: &self.achievedAt) }()
      case 9: try { try decoder.decodeSingularInt32Field(value: &self.score) }()
      case 10: try { try decoder.decodeSingularStringField(value: &self.clear) }()
      case 11: try { try decoder.decodeSingularStringField(value: &self.songID) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.profileID.isEmpty {
      try visitor.visitSingularStringField(value: self.profileID, fieldNumber: 1)
    }
    if !self.chartKey.isEmpty {
      try visitor.visitSingularStringField(value: self.chartKey, fieldNumber: 2)
    }
    if self.achievement.bitPattern != 0 {
      try visitor.visitSingularDoubleField(value: self.achievement, fieldNumber: 3)
    }
    if !self.rank.isEmpty {
      try visitor.visitSingularStringField(value: self.rank, fieldNumber: 4)
    }
    if self.dxScore != 0 {
      try visitor.visitSingularInt32Field(value: self.dxScore, fieldNumber: 5)
    }
    if !self.fc.isEmpty {
      try visitor.visitSingularStringField(value: self.fc, fieldNumber: 6)
    }
    if !self.fs.isEmpty {
      try visitor.visitSingularStringField(value: self.fs, fieldNumber: 7)
    }
    if self.achievedAt != 0 {
      try visitor.visitSingularInt64Field(value: self.achievedAt, fieldNumber: 8)
    }
    if self.score != 0 {
      try visitor.visitSingularInt32Field(value: self.score, fieldNumber: 9)
    }
    if !self.clear.isEmpty {
      try visitor.visitSingularStringField(value: self.clear, fieldNumber: 10)
    }
    if !self.songID.isEmpty {
      try visitor.visitSingularStringField(value: self.songID, fieldNumber: 11)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: RHYScore, rhs: RHYScore) -> Bool {
    if lhs.profileID != rhs.profileID {return false}
    if lhs.chartKey != rhs.chartKey {return false}
    if lhs.achievement != rhs.achievement {return false}
    if lhs.rank != rhs.rank {return false}
    if lhs.dxScore != rhs.dxScore {return false}
    if lhs.fc != rhs.fc {return false}
    if lhs.fs != rhs.fs {return false}
    if lhs.achievedAt != rhs.achievedAt {return false}
    if lhs.score != rhs.score {return false}
    if lhs.clear != rhs.clear {return false}
    if lhs.songID != rhs.songID {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension RHYPlayRecord: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".PlayRecord"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}id\0\u{1}result\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.id) }()
      case 2: try { try decoder.decodeSingularMessageField(value: &self._result) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.id.isEmpty {
      try visitor.visitSingularStringField(value: self.id, fieldNumber: 1)
    }
    try { if let v = self._result {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: RHYPlayRecord, rhs: RHYPlayRecord) -> Bool {
    if lhs.id != rhs.id {return false}
    if lhs._result != rhs._result {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension RHYCollection: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".Collection"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}id\0\u{1}name\0\u{3}sort_index\0\u{3}created_at\0\u{3}updated_at\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.id) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.name) }()
      case 3: try { try decoder.decodeSingularInt32Field(value: &self.sortIndex) }()
      case 4: try { try decoder.decodeSingularInt64Field(value: &self.createdAt) }()
      case 5: try { try decoder.decodeSingularInt64Field(value: &self.updatedAt) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.id.isEmpty {
      try visitor.visitSingularStringField(value: self.id, fieldNumber: 1)
    }
    if !self.name.isEmpty {
      try visitor.visitSingularStringField(value: self.name, fieldNumber: 2)
    }
    if self.sortIndex != 0 {
      try visitor.visitSingularInt32Field(value: self.sortIndex, fieldNumber: 3)
    }
    if self.createdAt != 0 {
      try visitor.visitSingularInt64Field(value: self.createdAt, fieldNumber: 4)
    }
    if self.updatedAt != 0 {
      try visitor.visitSingularInt64Field(value: self.updatedAt, fieldNumber: 5)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: RHYCollection, rhs: RHYCollection) -> Bool {
    if lhs.id != rhs.id {return false}
    if lhs.name != rhs.name {return false}
    if lhs.sortIndex != rhs.sortIndex {return false}
    if lhs.createdAt != rhs.createdAt {return false}
    if lhs.updatedAt != rhs.updatedAt {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension RHYCollectionItem: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".CollectionItem"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}id\0\u{3}collection_id\0\u{3}song_id\0\u{3}chart_type\0\u{1}difficulty\0\u{1}position\0\u{3}created_at\0\u{3}updated_at\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.id) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.collectionID) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.songID) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.chartType) }()
      case 5: try { try decoder.decodeSingularStringField(value: &self.difficulty) }()
      case 6: try { try decoder.decodeSingularInt32Field(value: &self.position) }()
      case 7: try { try decoder.decodeSingularInt64Field(value: &self.createdAt) }()
      case 8: try { try decoder.decodeSingularInt64Field(value: &self.updatedAt) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.id.isEmpty {
      try visitor.visitSingularStringField(value: self.id, fieldNumber: 1)
    }
    if !self.collectionID.isEmpty {
      try visitor.visitSingularStringField(value: self.collectionID, fieldNumber: 2)
    }
    if !self.songID.isEmpty {
      try visitor.visitSingularStringField(value: self.songID, fieldNumber: 3)
    }
    if !self.chartType.isEmpty {
      try visitor.visitSingularStringField(value: self.chartType, fieldNumber: 4)
    }
    if !self.difficulty.isEmpty {
      try visitor.visitSingularStringField(value: self.difficulty, fieldNumber: 5)
    }
    if self.position != 0 {
      try visitor.visitSingularInt32Field(value: self.position, fieldNumber: 6)
    }
    if self.createdAt != 0 {
      try visitor.visitSingularInt64Field(value: self.createdAt, fieldNumber: 7)
    }
    if self.updatedAt != 0 {
      try visitor.visitSingularInt64Field(value: self.updatedAt, fieldNumber: 8)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: RHYCollectionItem, rhs: RHYCollectionItem) -> Bool {
    if lhs.id != rhs.id {return false}
    if lhs.collectionID != rhs.collectionID {return false}
    if lhs.songID != rhs.songID {return false}
    if lhs.chartType != rhs.chartType {return false}
    if lhs.difficulty != rhs.difficulty {return false}
    if lhs.position != rhs.position {return false}
    if lhs.createdAt != rhs.createdAt {return false}
    if lhs.updatedAt != rhs.updatedAt {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension RHYSetting: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".Setting"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}key\0\u{1}kind\0\u{3}string_value\0\u{3}integer_value\0\u{3}double_value\0\u{3}bool_value\0\u{3}string_values\0\u{3}bytes_value\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.key) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.kind) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.stringValue) }()
      case 4: try { try decoder.decodeSingularInt64Field(value: &self.integerValue) }()
      case 5: try { try decoder.decodeSingularDoubleField(value: &self.doubleValue) }()
      case 6: try { try decoder.decodeSingularBoolField(value: &self.boolValue) }()
      case 7: try { try decoder.decodeRepeatedStringField(value: &self.stringValues) }()
      case 8: try { try decoder.decodeSingularBytesField(value: &self.bytesValue) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.key.isEmpty {
      try visitor.visitSingularStringField(value: self.key, fieldNumber: 1)
    }
    if !self.kind.isEmpty {
      try visitor.visitSingularStringField(value: self.kind, fieldNumber: 2)
    }
    if !self.stringValue.isEmpty {
      try visitor.visitSingularStringField(value: self.stringValue, fieldNumber: 3)
    }
    if self.integerValue != 0 {
      try visitor.visitSingularInt64Field(value: self.integerValue, fieldNumber: 4)
    }
    if self.doubleValue.bitPattern != 0 {
      try visitor.visitSingularDoubleField(value: self.doubleValue, fieldNumber: 5)
    }
    if self.boolValue != false {
      try visitor.visitSingularBoolField(value: self.boolValue, fieldNumber: 6)
    }
    if !self.stringValues.isEmpty {
      try visitor.visitRepeatedStringField(value: self.stringValues, fieldNumber: 7)
    }
    if !self.bytesValue.isEmpty {
      try visitor.visitSingularBytesField(value: self.bytesValue, fieldNumber: 8)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: RHYSetting, rhs: RHYSetting) -> Bool {
    if lhs.key != rhs.key {return false}
    if lhs.kind != rhs.kind {return false}
    if lhs.stringValue != rhs.stringValue {return false}
    if lhs.integerValue != rhs.integerValue {return false}
    if lhs.doubleValue != rhs.doubleValue {return false}
    if lhs.boolValue != rhs.boolValue {return false}
    if lhs.stringValues != rhs.stringValues {return false}
    if lhs.bytesValue != rhs.bytesValue {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
